### ISSUE TITLE
npm babel loader for browser use?

### ISSUE THREAD

**Issue by imylomylo** [montyanderson/stdrpc#11]
What's the secret for getting it to work in browser?

```
 error  in ./node_modules/stdrpc/index.js

Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
| 		url: "http://localhost:8332",
| 		methodTransform: a => a,
| 		..._config
| 	};
| 

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/AppHome.vue 200:0-28
 @ ./src/components/AppHome.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

I'm on the hunt atm.  Cheers

**Comment by imylomylo** [comment]
Using the babel plugin: `npm install --save-dev babel-preset-stage-3`which pulls in `transform-object-rest-spread` from the docs https://babeljs.io/docs/en/babel-preset-stage-3 gives same error in my project.

{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-3"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime", "transform-object-rest-spread"]
}

**Comment by imylomylo** [comment]
Got it to work in my project by `npm install --save /abs/path/to/stdrpc` after adding this to package.json and following some manual steps.

```
  "scripts": {
    "test": "mocha test/*.js",
    "coverage": "istanbul cover node_modules/mocha/bin/_mocha -- -R spec --exit",
    "babel": "babel --presets stage-3 index.js -o index.bundle.js"
  },
```
Need `npm install --save-dev babel-preset-stage-3`

and running `npm run babel`.   Then swapping index.js with index.bundle.js 
Bit cumbersome but it's what i need to get moving.

If anyone knows how to do this automatically in your own project for dependencies with webpack.  Be handy.

**Comment by montyanderson** [comment]
@imylomylo Just use an ES6+ compatible bundler. Browserify works nicely.
