### ISSUE TITLE
ZCash RPC Example

### ISSUE THREAD

**Issue by andrerfneves** [montyanderson/stdrpc#2]
Haven't used RPC interfaces with Bitcoin/Zcash before so I'm looking for some guidance on how to connect to the daemon using your library.

Followed your README notes, but running into this all the time:
```
rpc is Promise { <pending> }
(node:83939) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 401
```

Here's the node code:

```
const stdrpc = require('stdrpc');

const rpc = stdrpc('http://localhost:8232');
console.log('rpc is', rpc);

rpc.z_getbalance().then(balance => {
  console.log(balance);
});
```

Any idea why `rpc` is forever a `Promise`? 

Doing some documentation reading for Bitcoin/ZCash RPC and I believe I'm doing it correctly. Got the daemon running on port 8232 correctly as well.

Any pointers would be helpful! Cheers

**Comment by montyanderson** [comment]
Hi André,
401 is the http response code for '[unauthorized](https://httpstatuses.com/401)'.

I think you need to set your Zcash username and password like so:

``` javascript
const rpc = stdrpc('http://localhost:8232', {
    req: {
        auth: {
			username: "__username__",
			password: "__password__"
		}
    }
});
```
