### ISSUE TITLE
Is stdrpc still maintained?

### ISSUE THREAD

**Issue by ADumaine** [montyanderson/stdrpc#80]

**Comment by montyanderson** [comment]
I'm looking to pick this back up again @ADumaine.

Thanks for your patience!

**Comment by montyanderson** [comment]
@ADumaine Just pushed a new release with security updates.
Looking to become dependency-free in the future.

**Comment by ADumaine** [comment]
Thanks monty!
The old version of axios was an issue for us so we temporarily were using an updated branch.
Good to know this is updated now.
